//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Obligatorisk
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BookingSet()
        {
            this.VærktøjSet = new HashSet<VærktøjSet>();
        }
    
        public int BookingnummerID { get; set; }
        public System.DateTime Afhentningstidspunkt { get; set; }
        public int AntalDøgn { get; set; }
        public string Status { get; set; }
        public int KundeKundenummerID { get; set; }
    
        public virtual KundeSet KundeSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VærktøjSet> VærktøjSet { get; set; }
    }
}
