//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Obligatorisk
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VærktøjsudlejningEntities2 : DbContext
    {
        public VærktøjsudlejningEntities2()
            : base("name=VærktøjsudlejningEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BookingSet> BookingSet { get; set; }
        public virtual DbSet<KundeSet> KundeSet { get; set; }
        public virtual DbSet<VærktøjSet> VærktøjSet { get; set; }
    }
}
