//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Obligatorisk_ASP.NET_MVC_.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VærktøjsudlejningEntities : DbContext
    {
        public VærktøjsudlejningEntities()
            : base("name=VærktøjsudlejningEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Booking> BookingSet { get; set; }
        public virtual DbSet<Kunde> KundeSet { get; set; }
        public virtual DbSet<Værktøj> VærktøjSet { get; set; }
    }
}
